#!/usr/bin/env python
#!
#! E.G. ./doAction [Suspend | Hibernate | HybridSleep | PowerOff ...]
import sys

import dbus

def main(argv):

    bus = dbus.SystemBus()
    dbus_object = bus.get_object('org.freedesktop.login1',
                                 '/org/freedesktop/login1')
    dbus_iface = dbus.Interface(dbus_object, 'org.freedesktop.login1.Manager')
    command = "dbus_iface.{}(['True'])".format(argv[1])
    eval(command)

if __name__ == '__main__':
    main(sys.argv)
