#!/usr/bin/env python

import sys

import dbus

def main(argv):
    factory = dbus.SystemBus

    if len(argv) > 2:
        sys.exit(__doc__)
    elif len(argv) == 2:
        if argv[1] == '--session':
            factory = dbus.SessionBus
        elif argv[1] != '--system':
            sys.exit(__doc__)

    bus = factory()
    dbus_object = bus.get_object('org.freedesktop.login1',
                                 '/org/freedesktop/login1')
    dbus_iface = dbus.Interface(dbus_object, 'org.freedesktop.login1.Manager')
    dbus_iface.Hibernate(['True'])

if __name__ == '__main__':
    main(sys.argv)
